### PR TITLE
Unsigned Drivers

### PR DESCRIPTION
**Pull request by AndrewPla**
Added scanner for unsigned drivers.

### CODE REVIEW

**Comment by PDQ-Renzo** [comment]
This is awesome @AndrewPla , we tend to favor WMI when gathering information from the computers, was wondering if there was a specific need to use driverquery.exe as opposed to the WMI counterpart as it has a couple more fields that may be useful to have added to the results.

`Get-CimInstance -Query 'SELECT * FROM Win32_PnpSignedDriver WHERE IsSigned != TRUE'`

**Comment by AndrewPla** [comment]
@PDQ-Renzo  Nope, it was just what popped into my head and I didn't think about using PowerShell to get that info. I updated the command so that it's using WMI instead of driverquery.exe

**Comment by PDQ-Renzo** [comment]
@AndrewPla Sounds good, where there any fields that are preferred instead of grabbing all the fields? Also, it looks like by default it grabs the HTREE Device ID which shouldn't be needed as all computers have it unsigned.
`Get-CimInstance -Query 'SELECT * FROM Win32_PnpSignedDriver WHERE IsSigned != TRUE AND DeviceID != "HTREE\\ROOT\\0"'`

**Comment by AndrewPla** [comment]
I updated it so that it only outputs DeviceName, DeviceId, and PDO now.

**Review by PDQ-Zach — APPROVED** [review]
Requested changes were made

**Comment by PDQ-Zach** [comment]
Confirmed scanner works as expected in Inventory
All requested changes were made

**Pull request merged**
