### PR TITLE
Add WizTree scanners

### PR DESCRIPTION
**Pull request by ColbyBouma**
I think these would make a great blog post. 😉

### CODE REVIEW

**Comment by Jordan-PDQ** [comment]
This runs great, we did run into an issue with github desktop because it has a comma in it's path and made it throw an error. as that is the delimiter. Can you think of anything that might work around this very rare test case?

**Comment by ColbyBouma** [comment]
Weird, I thought I accounted for that. Can you post the full error and path please?

**Comment by Jordan-PDQ** [comment]
It looks like it splits it at "Github," and tries to convert " inc\" into an integer. I manually removed that comma and everything worked great. I can't think of any other application that puts a comma in it, and ironically I installed the application to test this pull request.

Path: 
C:\Users\user\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\ 

Error:
Cannot convert value " Inc\" to type "System.UInt64". Error: "Input string was not in a correct format."
At line:44 char:5
+     $FileName, [UInt64]$Size, $null = $Reader.ReadLine() -split ',' - ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToInteger

**Comment by ColbyBouma** [comment]
Ah, I see what the issue is. I assumed I didn't need "comma in the filename" handling in the User Profiles script, but I was wrong. I can fix that real quick.

**Comment by ColbyBouma** [comment]
OK, it should be fixed now 🤞

**Review by Jordan-PDQ — APPROVED** [review]
Changes work great. I think this is ready for live

**Comment by PDQ-Zach** [comment]
Andrew and I did a rebase and merge because Jordan said all was well

**Pull request merged**
